# Site settings
title: Chartbook Generator
description: > # this means to ignore newlines until "baseurl:"
  Meta description.
meta_image: cover-meta.png
url: "localhost:4000" # the base hostname & protocol for your site
baseurl: "/"
permalink: :title
twitter_username: taxfoundation
# Setup and configure collection for chartbook slides
collections:
  - slides
# Build settings
markdown: kramdown
kramdown:
  input: GFM
